### ISSUE TITLE
AWS: for i3 instances, use NVMe SSD

### ISSUE THREAD

**Issue by NikolayS** [startupturbo/nancy#34]
if we use i3 instance, then utilize c volumes that exist on i3 instances (but not mounted by default):

- [x] 1) add proper software and mount volume(s)  https://github.com/NikolayS/sysbench-tpcc/blob/master/aws_bench_pg.sh#L100 - example how to 

- [x] 2) ensure that `/var/lib/postgresql` will be places to /var/lib/postgresql

**Comment by dmius** [comment]
root@785970cfa36d:/# nvme list
/dev/nvme0n1: No such file or directory

**Comment by dmius** [comment]
https://github.com/startupturbo/nancy/pull/39

**Comment by NikolayS** [comment]
done?

**Comment by dmius** [comment]
Yes, merged
