### ISSUE TITLE
Nancy run: вывести количество ошибок

### ISSUE THREAD

**Issue by ane4ka** [startupturbo/nancy#40]
В минимальном результате вывести количество ошибок

**Comment by dmius** [comment]
https://github.com/startupturbo/nancy/blob/master/nancy_run.sh#L756

**Comment by NikolayS** [comment]
С другой стороны, если мы включим do-ddl/undo-ddl в отчёт, то это повлияет на его показатели. 

Похоже, лучше оставить как есть, не включать это в отчёт и summary, но ошибки do-ddl/undo-ddl считать фатальными и не продолжать выполнение, если они происходят.
